services:
  server:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - mongodb

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"